In [1]:
#step1:import pandas lib
import pandas as pd

In [2]:
#create a dictionary
data = {'Name': ['Alice','sai','sri','sam'],
        'Age': [25,26,27,28],
        'city': ['NewYork','London','Nepal','Chicago']
        }
data

{'Name': ['Alice', 'sai', 'sri', 'sam'],
 'Age': [25, 26, 27, 28],
 'city': ['NewYork', 'London', 'Nepal', 'Chicago']}

In [3]:
# convert dictionary to dataframe
df = pd.DataFrame(data)
df

    Name  Age     city
0  Alice   25  NewYork
1    sai   26   London
2    sri   27    Nepal
3    sam   28  Chicago

In [4]:
array_4d = [[[[1, 2], [3, 4], [5, 6], [7, 8]]],
             [[[9, 10], [11, 12]], [[13, 14],
                [15, 16]]]]
array_4d

[[[[1, 2], [3, 4], [5, 6], [7, 8]]],
 [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]

In [5]:
df_array=pd.DataFrame(array_4d,columns=['col1','col2'])
df_array

                               col1                  col2
0  [[1, 2], [3, 4], [5, 6], [7, 8]]                  None
1               [[9, 10], [11, 12]]  [[13, 14], [15, 16]]

In [6]:
#Method 2: Rename
df = df.rename(columns={'Name': 'Full Name', 'Age': 'Age in Years'})
df

  Full Name  Age in Years     city
0     Alice            25  NewYork
1       sai            26   London
2       sri            27    Nepal
3       sam            28  Chicago

In [7]:
df=pd.DataFrame(data,columns=['nt','age','city'])
df

    nt  age     city
0  NaN  NaN  NewYork
1  NaN  NaN   London
2  NaN  NaN    Nepal
3  NaN  NaN  Chicago

In [8]:
df_array.rename(columns={'col1':'firstcol','col2':'secondcol'})

                           firstcol             secondcol
0  [[1, 2], [3, 4], [5, 6], [7, 8]]                  None
1               [[9, 10], [11, 12]]  [[13, 14], [15, 16]]

In [39]:
import pandas as pd
df=pd.read_csv(r"C:\Tekworks\Day 5\dataset.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [21]:
df.head(2)
df.tail(1)
df.sample()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
161,55,0,1,132,342,0,1,166,0,1.2,2,0,2,1

In [40]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [41]:
# method 6 : describe()
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [45]:
#method 7 : find missing values
df.isnull().sum() #isna

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [34]:
#method 8 : value counts
df['age'].value_counts()

age
58    19
57    17
54    16
59    14
52    13
51    12
62    11
60    11
44    11
56    11
64    10
41    10
63     9
67     9
65     8
43     8
45     8
55     8
42     8
61     8
53     8
46     7
48     7
66     7
50     7
49     5
47     5
70     4
39     4
35     4
68     4
38     3
71     3
40     3
69     3
34     2
37     2
29     1
74     1
76     1
77     1
Name: count, dtype: int64

In [35]:
df['age'].value_counts().sum()

np.int64(303)

In [53]:
#method 9 : shape
df.shape

(303, 14)

In [55]:
#handled missing values
# #method 10 : fillna
df['age'].fillna('n0', inplace=True)

C:\Users\MAHIPALREDDY\AppData\Local\Temp\ipykernel_18740\3458812908.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna('n0', inplace=True)

In [49]:
#method 11: sort
df.sort_values(by='age', ascending=True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
58,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
239,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0
65,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1
129,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1
238,77,1,0,125,304,0,0,162,1,0.0,2,3,2,0

In [58]:
#method 12: groupby
df.groupby('sex').mean()

,age,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
sex,,,,,,,,,,,,,
0,55.677083,1.041667,133.083333,261.302083,0.12500,0.572917,151.125000,0.229167,0.876042,1.427083,0.552083,2.125000,0.750000
1,53.758454,0.932367,130.946860,239.289855,0.15942,0.507246,148.961353,0.371981,1.115459,1.386473,0.811594,2.400966,0.449275

In [59]:
df.groupby('sex')['age'].mean()

sex
0    55.677083
1    53.758454
Name: age, dtype: float64

In [61]:
df.groupby('sex')[['age','chol']].mean()

           age        chol
sex
0    55.677083  261.302083
1    53.758454  239.289855

In [66]:
#method 13 : iloc[start : end : position]
df.iloc[0:5, 0:3] #rows and cols

   age  sex  cp
0   63    1   3
1   37    1   2
2   41    0   1
3   56    1   1
4   57    0   0

In [67]:
#method 14 : loc
df.loc[0:5, ['age','sex','chol']]

   age  sex  chol
0   63    1   233
1   37    1   250
2   41    0   204
3   56    1   236
4   57    0   354
5   57    1   192

In [68]:
#method 15 : columns
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [69]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [73]:
# method 15 : astype
df['oldpeak']=df['oldpeak'].astype('int32')

In [74]:
df['oldpeak'].dtype

dtype('int32')

In [75]:
# method 16 : unique
df['sex'].unique()

array([1, 0])

In [76]:
# method 17: nunique()-count unique values
df['cp'].nunique()

4

In [78]:
#display age graeater than 20 (>20) and less tha 60 (<60)
#display how many persons 
df[(df['age'] > 20) &((df['age'] < 69))]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0,1,1,2,0

In [82]:
df[(df['chol'] > 200) &((df['chol'] < 200))]

Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target]
Index: []

In [85]:
df['chol']

0      233
1      250
2      204
3      236
4      354
      ...
298    241
299    264
300    193
301    131
302    236
Name: chol, Length: 303, dtype: int64

In [88]:
df["chol_level"]=df["chol"].apply(
    lambda x: "hii" if x < 200 else "hlo"
)
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,chol_status,chol_lavel,chol_level
0,63,1,3,145,233,1,0,150,0,2,0,0,1,1,hlo,hlo,hlo
1,37,1,2,130,250,0,1,187,0,3,0,0,2,1,hlo,hlo,hlo
2,41,0,1,130,204,0,0,172,0,1,2,0,2,1,hlo,hlo,hlo
3,56,1,1,120,236,0,1,178,0,0,2,0,2,1,hlo,hlo,hlo
4,57,0,0,120,354,0,1,163,1,0,2,0,2,1,hlo,hlo,hlo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0,1,0,3,0,hlo,hlo,hlo
299,45,1,3,110,264,0,1,132,0,1,1,0,3,0,hlo,hlo,hlo
300,68,1,0,144,193,1,1,141,0,3,1,2,3,0,hii,hii,hii
301,57,1,0,130,131,0,1,115,1,1,1,1,3,0,hii,hii,hii
302,57,0,1,130,236,0,0,174,0,0,1,1,2,0,hlo,hlo,hlo